### ISSUE TITLE
[First iteration] 

### ISSUE THREAD

**Issue by giogonzo** [buildo/ste-gh-explorer#2]
## requirements
After this iteration the user should be able to enter see the app, search for a repo in the nav bar and see the results (if any) of the search.

The page layout should have a navbar and a body. See the mockup for further details.

## sub-issues

- [x] Main layout structure #3 **[armoniaechaos]**
- [x] Implement NavBar #4 **[armoniaechaos]**
- [x] Implement Results Panel #5 **[armoniaechaos]**

## mockup
![image](https://cloud.githubusercontent.com/assets/4029499/12507566/d5aacfac-c0f6-11e5-8ed4-ed8411e97214.png)
